export const LONGEST_ROAD_MINIMUM_LENGTH = 5
export const LARGEST_ARMY_MINIMUM_KNIGHTS = 3
export const LONGEST_ROAD_VICTORY_POINTS = 2
export const LARGEST_ARMY_VICTORY_POINTS = 2
export const SETTLEMENT_VICTORY_POINTS = 1
export const CITY_VICTORY_POINTS = 2
export const VICTORY_POINT_CARD_POINTS = 1
export const STANDARD_VICTORY_POINT_TARGET = 10
